# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_Mbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mbox(object):
    def setupUi(self, Mbox):
        Mbox.setObjectName("Mbox")
        Mbox.resize(253, 288)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../收藏夹/iCloud Photos/Downloads/2019/IMG_0574.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Mbox.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Mbox)
        self.centralwidget.setObjectName("centralwidget")
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setGeometry(QtCore.QRect(70, 240, 71, 28))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(160, 240, 71, 28))
        self.cancelButton.setObjectName("cancelButton")
        self.msg = QtWidgets.QLabel(self.centralwidget)
        self.msg.setGeometry(QtCore.QRect(40, 10, 201, 16))
        self.msg.setObjectName("msg")
        self.nanButton = QtWidgets.QRadioButton(self.centralwidget)
        self.nanButton.setGeometry(QtCore.QRect(100, 120, 41, 19))
        self.nanButton.setObjectName("nanButton")
        self.nvButton = QtWidgets.QRadioButton(self.centralwidget)
        self.nvButton.setGeometry(QtCore.QRect(170, 120, 41, 19))
        self.nvButton.setObjectName("nvButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(15, 51, 61, 16))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(15, 159, 61, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.MnameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.MnameEdit.setGeometry(QtCore.QRect(85, 87, 146, 21))
        self.MnameEdit.setClearButtonEnabled(True)
        self.MnameEdit.setObjectName("MnameEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(15, 87, 61, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(15, 123, 61, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(15, 195, 60, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.MnoEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.MnoEdit.setGeometry(QtCore.QRect(85, 51, 146, 21))
        self.MnoEdit.setReadOnly(False)
        self.MnoEdit.setClearButtonEnabled(True)
        self.MnoEdit.setObjectName("MnoEdit")
        self.MageEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.MageEdit.setGeometry(QtCore.QRect(85, 159, 146, 21))
        self.MageEdit.setClearButtonEnabled(True)
        self.MageEdit.setObjectName("MageEdit")
        self.MphonEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.MphonEdit.setGeometry(QtCore.QRect(85, 195, 146, 21))
        self.MphonEdit.setClearButtonEnabled(True)
        self.MphonEdit.setObjectName("MphonEdit")
        Mbox.setCentralWidget(self.centralwidget)

        self.retranslateUi(Mbox)
        QtCore.QMetaObject.connectSlotsByName(Mbox)

    def retranslateUi(self, Mbox):
        _translate = QtCore.QCoreApplication.translate
        Mbox.setWindowTitle(_translate("Mbox", "工作人员信息盒"))
        self.okButton.setText(_translate("Mbox", "确定"))
        self.cancelButton.setText(_translate("Mbox", "取消"))
        self.msg.setText(_translate("Mbox", "提示信息"))
        self.nanButton.setText(_translate("Mbox", "男"))
        self.nvButton.setText(_translate("Mbox", "女"))
        self.label.setText(_translate("Mbox", "工号"))
        self.label_4.setText(_translate("Mbox", "年龄"))
        self.label_2.setText(_translate("Mbox", "姓名"))
        self.label_3.setText(_translate("Mbox", "性别"))
        self.label_5.setText(_translate("Mbox", "联系方式"))
