# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_Sbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sbox(object):
    def setupUi(self, Sbox):
        Sbox.setObjectName("Sbox")
        Sbox.resize(272, 330)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../收藏夹/iCloud Photos/Downloads/2019/IMG_0574.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Sbox.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Sbox)
        self.centralwidget.setObjectName("centralwidget")
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setGeometry(QtCore.QRect(80, 290, 71, 28))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(170, 290, 71, 28))
        self.cancelButton.setObjectName("cancelButton")
        self.msg = QtWidgets.QLabel(self.centralwidget)
        self.msg.setGeometry(QtCore.QRect(40, 10, 201, 16))
        self.msg.setObjectName("msg")
        self.LocationEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.LocationEdit.setGeometry(QtCore.QRect(110, 243, 131, 21))
        self.LocationEdit.setClearButtonEnabled(True)
        self.LocationEdit.setObjectName("LocationEdit")
        self.SnoEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.SnoEdit.setGeometry(QtCore.QRect(110, 91, 131, 21))
        self.SnoEdit.setClearButtonEnabled(True)
        self.SnoEdit.setObjectName("SnoEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(25, 167, 71, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(25, 91, 71, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(25, 129, 75, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(25, 243, 71, 16))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.K_nEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.K_nEdit.setGeometry(QtCore.QRect(110, 129, 131, 21))
        self.K_nEdit.setClearButtonEnabled(True)
        self.K_nEdit.setObjectName("K_nEdit")
        self.L_nEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.L_nEdit.setGeometry(QtCore.QRect(110, 167, 131, 21))
        self.L_nEdit.setClearButtonEnabled(True)
        self.L_nEdit.setObjectName("L_nEdit")
        self.C_nEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.C_nEdit.setGeometry(QtCore.QRect(110, 205, 131, 21))
        self.C_nEdit.setClearButtonEnabled(True)
        self.C_nEdit.setObjectName("C_nEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(25, 205, 71, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.Lnodit = QtWidgets.QLineEdit(self.centralwidget)
        self.Lnodit.setGeometry(QtCore.QRect(110, 53, 131, 21))
        self.Lnodit.setReadOnly(False)
        self.Lnodit.setClearButtonEnabled(True)
        self.Lnodit.setObjectName("Lnodit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(25, 53, 71, 16))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        Sbox.setCentralWidget(self.centralwidget)

        self.retranslateUi(Sbox)
        QtCore.QMetaObject.connectSlotsByName(Sbox)

    def retranslateUi(self, Sbox):
        _translate = QtCore.QCoreApplication.translate
        Sbox.setWindowTitle(_translate("Sbox", "宿舍信息盒"))
        self.okButton.setText(_translate("Sbox", "确定"))
        self.cancelButton.setText(_translate("Sbox", "取消"))
        self.msg.setText(_translate("Sbox", "提示信息"))
        self.label_4.setText(_translate("Sbox", "入住人数"))
        self.label_2.setText(_translate("Sbox", "宿舍号"))
        self.label_3.setText(_translate("Sbox", "可容纳人数"))
        self.label_6.setText(_translate("Sbox", "位置"))
        self.label_5.setText(_translate("Sbox", "剩余空位"))
        self.label.setText(_translate("Sbox", "楼号"))
